#Imperative command to create service to expose frontend deployment 
#kubectl expose deploy api \ --name=api \ --type=LoadBalancer \ --port=80 \ --target-port=8080
#apiVersion: v1
#kind: Service
#metadata:
 # name: api
  #labels:
   # app: api
#spec:
 # selector:
  #  app: api
  #ports:
   # - protocol: TCP
    #  port: 80
     # targetPort: 8080
  #type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # You can specify any port in the range 30000-32767
  type: NodePort
